# Generated by Django 3.2.3 on 2021-10-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20211009_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='comment/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='business_close_hour',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='business_open_hour',
            field=models.CharField(max_length=30),
        ),
    ]
