# Generated by Django 3.2.7 on 2021-10-25 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20211013_1802'),
        ('restaurant', '0006_auto_20211014_1124'),
    ]

    operations = [
    ]
