# Generated by Django 2.2.20 on 2021-10-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20211013_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodmenu',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='business_close_hour',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='business_open_hour',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='business_hour',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
